# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            devinl.im
tagline:          Devin Lim
description:      'Linux enthusiast
                  <br>
                  <div class="flag"><img src="/public/icons/id.ico"></div>    
                  <div class="flag"><img src="/public/icons/my.ico"></div>    
                  <div class="flag"><img src="/public/icons/au.ico"></div>    
                  <div class="flag"><img src="/public/icons/us.ico"></div>
                  <br>
                  Previously
                  <br>
                  <a href="https://amazon.care">@Amazon</a> & <a href="https://polyverse.com/">@Polyverse</a>'
url:              https://devinl.im
baseurl:          /

author:
  name:           'Devin Lim'
  url:            https://www.linkedin.com/in/ayydavay/
  email:          devin@devinl.im

paginate:         5

instagram:
  url:            https://www.instagram.com/ayydavay/
  
linkedin:
  url:            https://linkedin.com/in/ayydavay

github:
  url:            https://github.com/davay
  repo:           https://github.com/davay/davay.github.io

plugins: [jekyll-paginate, jekyll-gist, jekyll-seo-tag]
